defaults: &defaults
  update_supervisor_params:
    - supervisor
    - leader
  languages:
    en: "en"
    jp: "ja"
  tasks:
    values:
      init: 0
      started: 1
      in_progress: 2
      resolved: 3
      closed: 4
    statuses:
      init: "New"
      in_progress: "In progress"
      closed: "Closed"
      started: "Started"
      resolved: "Resolved"
  flag_size: "20x15"
  image_user_size: "30x30"
  finish: "finish"
  finished: "finished"
  date_format: "%H:%M:%S %-d %B %Y"
  date_course_format: "%-d %B %Y"
  course_subject:
    finish: "finish"
    start: "progress"
  form:
    field_size: 50
  position:
    check_position: 0
    index: 1
development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
